// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCwZEnCyyYEiY0X9YWB3i_VYOMmC-v3o0w',
    appId: '1:136537596969:web:5a984e87e53ac69022a838',
    messagingSenderId: '136537596969',
    projectId: 'medicnest-jaspa',
    authDomain: 'medicnest-jaspa.firebaseapp.com',
    storageBucket: 'medicnest-jaspa.appspot.com',
    measurementId: 'G-6NFJ51YGRK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyATe15S9XzvSkyS8E-5YAeUO_xl93kJZH4',
    appId: '1:136537596969:android:f40718ee4abecb0622a838',
    messagingSenderId: '136537596969',
    projectId: 'medicnest-jaspa',
    storageBucket: 'medicnest-jaspa.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAq553gIaTvNwAuCiZCw6kbh4OFx-IQQIs',
    appId: '1:136537596969:ios:60c9575380212e9922a838',
    messagingSenderId: '136537596969',
    projectId: 'medicnest-jaspa',
    storageBucket: 'medicnest-jaspa.appspot.com',
    iosBundleId: 'za.co.medicnest.patientApp',
  );
}
